version: 0.2

phases:
  build:
    runtime-versions:
      python: 3.10
    commands:
      # CDK Version is defaulted to 2.82.0 if not mentioned using `-c`
      # Rosbag Image Pipeline
      - apt-get update -y && apt-get install -y net-tools
      - bash gen-reports.sh -m analysis/rosbag-image-pipeline -r requirements-dev.txt
      # Storage
      - bash gen-reports.sh -m core/metadata-storage
      # Integration
      - bash gen-reports.sh -m integration/ddb-to-opensearch
      - bash gen-reports.sh -m integration/opensearch-tunnel
      # Optionals
      - bash gen-reports.sh -m optionals/datalake-buckets
      # Post Processing
      - bash gen-reports.sh -m post-processing/yolo-object-detection
      - bash gen-reports.sh -m post-processing/yolop-lane-detection
      # Sensor Extraction
      - bash gen-reports.sh -m sensor-extraction/ros-to-parquet -c 2.70.0 #Breaking changes from 2.82.0
      - bash gen-reports.sh -m sensor-extraction/ros-to-png -c 2.70.0 #Breaking changes from 2.82.0
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'