name: example-dags
path: modules/examples/example-dags/
parameters:
  - name: dag-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: ArtifactsBucketName
  - name: dag-path
    valueFrom:
      moduleMetadata:
        group: core
        name: mwaa
        key: DagPath
  - name: mwaa-exec-role-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: mwaa
        key: MwaaExecRoleArn
  - name: bucket-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
---
name: docker-build
path: modules/examples/docker-build/
parameters:
  - name: ecr-repo-name
    value: python-sample-app
# ---
# name: tf-pattern
# path: modules/examples/example-tf/
# parameters:
#   - name: tf-s3-bucket
#     value: "addf-tfstate"
#   - name: tf-ddb-table
#     value: "addf-tfstate-lock"
#   # Comment the above and Uncomment the below if you want to fetch the s3 and ddb tables created by the tf-prereqs module
#   # - name: tf-s3-bucket
#   #   valueFrom:
#   #     moduleMetadata:
#   #       group: prereqs
#   #       name: tf-prereqs
#   #       key: TfStateBucketName
#   # - name: tf-ddb-table
#   #   valueFrom:
#   #     moduleMetadata:
#   #       group: prereqs
#   #       name: tf-prereqs
#   #       key: TfLockTable