name: Sync GitHub with AWS CodeCommit for AV/ADAS Solutions

on:
  # Triggers the workflow on push or pull request events but only for the "av-adas-solution" branch
  push:
    branches: ["av-adas-solution"]
  pull_request:
    branches: ["av-adas-solution"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  sync:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/addf-sonarscan-branch'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::180024969694:role/GitHubAction-AssumeRoleWithAction #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-west-2
      - name: Install utilities
        run: |
          pip install git-remote-codecommit
          git clone codecommit::us-west-2://av-adas-solution
          ls -al
          ls -al av-adas-solution

          echo "Copying modules one after the other"
          # Analysis
          cp -R modules/analysis/rosbag-image-pipeline av-adas-solution/modules/analysis/
          # Core
          cp -R modules/core/metadata-storage av-adas-solution/modules/core
          # Integration
          cp -R modules/integration/ddb-to-opensearch av-adas-solution/modules/integration
          cp -R modules/integration/opensearch-tunnel av-adas-solution/modules/integration
          # Optionals
          cp -R modules/optionals/datalake-buckets av-adas-solution/modules/optionals
          # Post processing
          cp -R modules/post-processing/yolo-object-detection av-adas-solution/modules/post-processing
          cp -R modules/post-processing/yolop-lane-detection av-adas-solution/modules/post-processing
          # Sensor extraction
          cp -R modules/sensor-extraction/ros-to-parquet av-adas-solution/modules/sensor-extraction
          cp -R modules/sensor-extraction/ros-to-png av-adas-solution/modules/sensor-extraction
          ls -al av-adas-solution/modules/
          echo "Copied modules"

          echo "Copying Manifest file contents..."
          cp -R manifests/aws-solutions/ av-adas-solution/manifests/aws-solutions/

          cd av-adas-solution/
          git config --global user.email "ssriche@amazon.com"
          git config --global user.name "Srinivas"
          git config --global init.defaultBranch main
          git branch -a
          git add -A
          git status
          git commit -m "sync gh with cc"
          git remote -v
          git status
          git push origin main
