name: ros-to-parquet
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/sensor-extraction/ros-to-parquet/?ref=scene-intelligence-with-rosbag-on-aws
parameters:
  - name: platform
    value: FARGATE
  - name: retries
    value: 1
  - name: timeout-seconds
    value: 1800
  - name: vcpus
    value: 2
  - name: memory-mib
    value: 8192
  - name: removal-policy
    value: DESTROY
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
  - name: solution-id
    value: 'SO0279'
  - name: solution-name
    value: 'Scene Intelligence with Rosbag on AWS'
  - name: solution-version
    value: v1.0.0
---
name: ros-to-png
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/sensor-extraction/ros-to-png/?ref=scene-intelligence-with-rosbag-on-aws
parameters:
  - name: platform
    value: FARGATE
  - name: retries
    value: 1
  - name: timeout-seconds
    value: 1800
  - name: vcpus
    value: 2
  - name: memory-mib
    value: 8192
  - name: resized-width
    value: 1280
  - name: resized-height
    value: 720
  - name: removal-policy
    value: DESTROY
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
  - name: solution-id
    value: 'SO0279'
  - name: solution-name
    value: 'Scene Intelligence with Rosbag on AWS'
  - name: solution-version
    value: v1.0.0
---
name: object-detection
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/post-processing/yolo-object-detection/?ref=scene-intelligence-with-rosbag-on-aws
parameters:
  - name: removal-policy
    value: DESTROY
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
  - name: solution-id
    value: 'SO0279'
  - name: solution-name
    value: 'Scene Intelligence with Rosbag on AWS'
  - name: solution-version
    value: v1.0.0
---
name: lane-detection
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/post-processing/yolop-lane-detection/?ref=scene-intelligence-with-rosbag-on-aws
parameters:
  - name: removal-policy
    value: DESTROY
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
  - name: solution-id
    value: 'SO0279'
  - name: solution-name
    value: 'Scene Intelligence with Rosbag on AWS'
  - name: solution-version
    value: v1.0.0