name: opensearch-proxy
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/demo-only/opensearch-proxy/?ref=release/2.0.0
parameters:
  - name: opensearch-domain-endpoint
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainEndpoint
  - name: opensearch-sg-id
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchSecurityGroupId
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: secrets-manager-name
    value: opensearch-proxy-credentials
---
name: rosbag-ddb-to-os
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/integration/ddb-to-opensearch/?ref=release/2.0.0
parameters:
  - name: opensearch-domain-name
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainName
  - name: opensearch-domain-endpoint
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainEndpoint
  - name: opensearch-sg-id
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchSecurityGroupId
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: rosbag_stream_arn
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: RosbagSceneMetadataStreamArn