name: networking
path: git::codecommit::us-west-2://av-adas-solution.git//modules/network/basic-cdk/?ref=main
parameters:
  - name: internet-accessible
    value: true
---
name: datalake-buckets
path: git::codecommit::us-west-2://av-adas-solution.git//modules/optionals/datalake-buckets/?ref=main
parameters:
  - name: encryption-type
    value: SSE
